import turtle
screen = turtle.Screen()
screen.bgcolor("white")
pen = turtle.Turtle()
pen.color("red")
pen.pensize(2)
pen.speed(2)
pen.begin_fill()
pen.fillcolor("red")
pen.left(140)
pen.forward(180)
pen.circle(-90, 200)
pen.left(120)
pen.circle(-90, 200)
pen.forward(180)
pen.end_fill()
pen.up()
pen.goto(-30, 130)
pen.down()
pen.color("white")
pen.write("Made with ❤", font=("Arial", 14, "bold"))
pen.hideturtle()
screen.mainloop()